site:
  logo: 北京合安福科技有限公司
  title: "北京合安福科技有限公司"
  keywords: IT、互联网、GIS、地理信息技术、3S技术、IT计算机服务
  description: 北京合安福科技有限公司是IT软件信息服务、先进的地理信息服务提供商，为客户提供高效、优质的软硬件互联网服务。

post:
  # 文章模块标题
  title: 公司新闻
  # 文章模块副标题
  # description: 北京合安福科技有限公司是IT软件信息服务、先进的地理信息服务提供商，为客户提供高效、优质的软硬件互联网服务。

# project属性
project:
  title: 公司项目
	date: 项目创建时间
	description: 项目描述
	home_url: 项目主页
  # demo_url: 演示地址 or 下载链接
  
banner:
  title: 北京合安福科技有限公司
  description: 北京合安福科技有限公司是IT软件信息服务、先进的地理信息服务提供商，为客户提供高效、优质的软硬件互联网服务。
  background_image: /images/banner-bg.jpg, /images/banner-bg.3jpg, /images/banner-bg2.jpg

author:
  avatar: "/images/avatar.gif"
  nick: "北京合安福科技有限公司"
  description: "北京合安福科技有限公司是IT软件信息服务、先进的地理信息服务提供商，为客户提供高效、优质的软硬件互联网服务。"

# main menu navigation
menu:
  首页: /
  新闻: /post/index.html
  解决方案: /project/index.html
  关于我们: /2019/06/05/about/
  # 关于我们: /about.html
  # Minimal: /project/2016/04/28/hexo-minimal.html

preview: true
comments: false
menu_icons:
  Minimal: tachometer

# 集成第三方服务
vendors:
  # 社会化评论， 畅言
  # changyan:
  #   app_id: cysYE5nWR
  #   conf: prod_ea59e8a942c2c4c0e72b24ed00ecddc9
